version: '3.8'
services:
  postgres_dev:
    image: postgres:14
    container_name: encafeinados_app_db_dev
    restart: always
    environment:
      POSTGRES_USER: encafeinados
      POSTGRES_PASSWORD: encafeinados123
      POSTGRES_DB: encafeinados_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
  postgres_data_test:
